extends: []
rules:
  agb-info-version:
    description: info.version must exist
    given: "$.info"
    then:
      field: "version"
      function: truthy
  agb-paths-present:
    description: paths must exist
    given: "$"
    then:
      field: "paths"
      function: truthy

