#!/usr/bin/env python3
import argparse
import json
import re
import sys
from pathlib import Path

import yaml


def load_config() -> dict:
  return json.loads(Path("docs/ops/ai-team-config.json").read_text(encoding="utf-8"))


def generate_web_client(openapi: dict, out_dir: Path) -> None:
  out_dir.mkdir(parents=True, exist_ok=True)

  lines: list[str] = []
  lines.append("// Generated by ContractSync. DO NOT EDIT.")
  lines.append('import { http } from "../http.js";')
  lines.append("")

  paths = openapi.get("paths", {})
  if isinstance(paths, dict):
    for p, item in paths.items():
      if not isinstance(item, dict):
        continue
      for method, op in item.items():
        if method not in ("get", "post", "put", "delete"):
          continue
        if not isinstance(op, dict):
          continue
        op_id = op.get("operationId")
        if isinstance(op_id, str) and re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", op_id):
          fn_name = op_id
        else:
          safe = re.sub(r"[^a-zA-Z0-9]+", "_", f"{method}_{p}".strip("/")) or "call"
          fn_name = safe
        lines.append(f"export async function {fn_name}(params) {{")
        if method == "get":
          lines.append(f'  const res = await http.get("{p}", {{ params }});')
        else:
          lines.append(f'  const res = await http.{method}("{p}", params);')
        lines.append("  return res.data;")
        lines.append("}")
        lines.append("")

  Path(out_dir / "index.js").write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
  ap = argparse.ArgumentParser(description="Skill: ContractSync (check + optional codegen)")
  ap.add_argument("action", choices=["check", "generate"], help="check: run contract-check; generate: codegen from openapi")
  args = ap.parse_args()

  cfg = load_config()
  if args.action == "check":
    # Delegates to gate script to keep single entry.
    import subprocess

    r = subprocess.run(["./scripts/contract-check"])
    return r.returncode

  openapi_path = Path(cfg["contracts"]["openapiPath"])
  openapi = yaml.safe_load(openapi_path.read_text(encoding="utf-8"))
  out_dir = Path(cfg["contracts"]["generated"]["webClientOutDir"])
  generate_web_client(openapi, out_dir)
  print(f"GENERATED_OK {out_dir}")
  return 0


if __name__ == "__main__":
  raise SystemExit(main())
